spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
  jackson:
    time-zone: Asia/Seoul

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

notion:
  token: ${NOTION_API_TOKEN}
  feedback_database_id: ${NOTION_FEEDBACK_DATABASE_ID}
  report_database_id: ${NOTION_REPORT_DATABASE_ID}
  report_database_leenk_id: ${NOTION_REPORT_DATABASE_LEENK_ID}
  version: ${NOTION_VERSION}

slack:
  webhook_url: ${SLACK_WEBHOOK_URL}

token:
  access_token: ${ACCESS_TOKEN}
  refresh_token: ${REFRESH_TOKEN}
  password: ${PASSWORD}
